const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL = s => {try{const u=new URL(s,document.baseURI);return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
const imageURL = s => /^data:image\/(jpeg|png|webp);base64,/.test(s||'')?s:safeURL(s);

const page=location.pathname.split('/').pop().replace('.html','')||'index';
let data,shownPhotos=[],viewer=[],photoIndex=0,toastTimer;
function newestFirst(items){return items.sort((a,b)=>(Date.parse(b.createdAt)||0)-(Date.parse(a.createdAt)||0))}
function publicationYear(p){return /^\d{4}$/.test(String(p.year))?Number(p.year):0}
function papersByYear(items){return items.sort((a,b)=>publicationYear(b)-publicationYear(a)||(Date.parse(b.createdAt)||0)-(Date.parse(a.createdAt)||0))}
function imagesOf(p){return Array.isArray(p.images)&&p.images.length?p.images:p.src?[{src:p.src,alt:p.alt||p.title}]:[]}
function normalize(d){d.profile ||= {};d.profile.links ||= [];d.profile.headerName ??= d.profile.name||'Blue hour';d.photos ||= [];d.papers ||= [];d.works ||= [];d.photos.forEach((p,i)=>p.id ||= 'legacy-photo-'+i);d.works.forEach((p,i)=>p.id ||= 'legacy-work-'+i);newestFirst(d.photos);papersByYear(d.papers);newestFirst(d.works);return d}
const pdfBlobs=new Map();
function pdfURL(value){if(!/^data:application\/pdf;base64,/.test(value||''))return safeURL(value);if(!pdfBlobs.has(value)){try{const bytes=Uint8Array.from(atob(value.split(',')[1]),c=>c.charCodeAt(0));pdfBlobs.set(value,URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})))}catch{return '#'}}return pdfBlobs.get(value)}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,5000)}
function intro(kicker,title,description){return `<section class="page-intro"><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${esc(description)}</p></section>`}
function featuredPhoto(){for(const post of data.photos){const images=imagesOf(post);for(let i=0;i<images.length;i++)if(`${post.id}::${i}`===data.profile.featuredPhoto)return {...post,...images[i]}}const p=data.photos[0];return p?{...p,...imagesOf(p)[0]}:null}
function photoCard(p,i){const images=imagesOf(p);return `<article class="photo-card"><button class="photo-button" data-photo="${i}" aria-label="View ${esc(p.title)}"><img src="${esc(imageURL(images[0]?.src))}" alt="${esc(images[0]?.alt||p.title)}" loading="lazy" width="900" height="1100"><span class="image-count">${images.length>1?images.length+' photographs':'View photograph'} ↗</span></button><div class="photo-info"><h3>${esc(p.title)}</h3><span>${esc(p.category)}</span></div>${p.caption?`<p class="photo-story">${esc(p.caption)}</p>`:''}</article>`}
function gallery(photos,full=false){shownPhotos=photos;return `<div class="gallery ${full?'full-gallery':''}">${photos.map(photoCard).join('')}</div>`}
function demoNote(){return data.photos.some(p=>p.demo)?'<p class="demo-note">Demo imagery · Credited to the original Unsplash photographers in the viewer.</p>':''}
function paperCard(p,i){return `<article class="paper"><div class="paper-year">${esc(p.year||'Undated')}</div><div><div class="eyebrow">${esc(p.type||'Publication')}</div><h2>${esc(p.title)}</h2><div class="meta">${esc(p.authors)}${p.venue?' · '+esc(p.venue):''}</div>${p.abstract?`<details><summary>Read abstract</summary><p>${esc(p.abstract)}</p></details>`:''}<div class="paper-actions">${p.url?`<a class="text-link" href="${esc(safeURL(p.url))}" target="_blank" rel="noopener noreferrer">Read paper ↗</a><button data-share="${i}">Share link</button>`:''}${p.pdf?`<a class="text-link" href="${esc(pdfURL(p.pdf))}" target="_blank" rel="noopener noreferrer">PDF ↗</a>`:''}</div></div><span class="paper-arrow" aria-hidden="true">↗</span></article>`}

function homeGallery(photos){
  shownPhotos=photos;
  if(photos.length<2)return gallery(photos);
  return '<div class="photo-carousel" role="region" aria-label="Selected photographs">'+
    '<div class="carousel-toolbar"><span class="carousel-hint">A few moments, passing by.</span><div class="carousel-controls">'+
    '<button type="button" class="carousel-toggle" aria-controls="photo-rail">Pause scrolling</button>'+
    '<button type="button" class="carousel-prev" aria-label="Previous photograph" aria-controls="photo-rail">←</button>'+
    '<button type="button" class="carousel-next" aria-label="Next photograph" aria-controls="photo-rail">→</button></div></div>'+
    '<div id="photo-rail" class="photo-rail" tabindex="0" aria-label="Photographs; use arrow keys or swipe to browse"><div class="carousel-track"><div class="carousel-group">'+photos.map(photoCard).join('')+'</div></div></div></div>';
}
function enhancePhotoCarousel(){
  const carousel=document.querySelector('.photo-carousel');if(!carousel)return;
  const rail=carousel.querySelector('.photo-rail'),track=carousel.querySelector('.carousel-track'),group=track.firstElementChild;
  const toggle=carousel.querySelector('.carousel-toggle'),motion=matchMedia('(prefers-reduced-motion: reduce)');
  let paused=motion.matches,hovered=false,focused=false,visible=false,cycle=0,position=0,last=0;
  const label=()=>{toggle.textContent=paused?'Play scrolling':'Pause scrolling';carousel.dataset.paused=String(paused)};
  const pause=()=>{paused=true;label()};
  const wrap=value=>cycle?((value%cycle)+cycle)%cycle:0;
  const rebuild=()=>{
    track.querySelectorAll('[data-clone]').forEach(el=>el.remove());
    cycle=group.getBoundingClientRect().width;if(!cycle)return;
    const copies=Math.ceil(rail.clientWidth/cycle)+1;
    for(let i=0;i<copies;i++){
      const clone=group.cloneNode(true);clone.dataset.clone='true';clone.setAttribute('aria-hidden','true');
      clone.querySelectorAll('button').forEach(button=>{button.tabIndex=-1;button.addEventListener('mousedown',event=>event.preventDefault())});
      track.append(clone);
    }
    position=wrap(rail.scrollLeft);rail.scrollLeft=position;bindPhotoButtons();
  };
  toggle.onclick=()=>{paused=!paused;position=wrap(rail.scrollLeft);rail.scrollLeft=position;label()};
  const step=direction=>{pause();const card=group.firstElementChild;position=wrap(rail.scrollLeft+direction*(card.getBoundingClientRect().width+24));rail.scrollLeft=position};
  carousel.querySelector('.carousel-prev').onclick=()=>step(-1);
  carousel.querySelector('.carousel-next').onclick=()=>step(1);
  rail.addEventListener('mouseenter',()=>{hovered=true});rail.addEventListener('mouseleave',()=>{hovered=false;position=rail.scrollLeft});
  rail.addEventListener('focusin',()=>{focused=true});rail.addEventListener('focusout',()=>{focused=rail.contains(document.activeElement);position=rail.scrollLeft});
  rail.addEventListener('pointerdown',pause,{passive:true});rail.addEventListener('wheel',pause,{passive:true});
  rail.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();step(event.key==='ArrowLeft'?-1:1)}});
  motion.addEventListener('change',()=>{if(motion.matches)pause()});
  new ResizeObserver(rebuild).observe(rail);
  new IntersectionObserver(entries=>{visible=entries[0].isIntersecting}).observe(rail);
  function frame(now){
    const dt=Math.min((now-last)/1000,.05);last=now;
    if(!paused&&!hovered&&!focused&&visible&&!document.hidden&&!document.querySelector('dialog[open]')&&cycle){
      position=wrap(position+18*dt);rail.scrollLeft=position;
    }else position=rail.scrollLeft;
    requestAnimationFrame(frame);
  }
  label();rebuild();requestAnimationFrame(frame);
}

function homePhotos(){const featured=featuredPhoto();if(!featured)return [];const post=data.photos.find(p=>p.id===featured.id);const imgs=imagesOf(post);const chosen=imgs.findIndex(i=>i.src===featured.src);return [{...post,images:chosen>0?[imgs[chosen],...imgs.filter((_,i)=>i!==chosen)]:imgs},...data.photos.filter(p=>p.id!==post.id)].slice(0,3)}
function photography(){const categories=['All',...new Set(data.photos.map(p=>p.category).filter(Boolean))];return `${intro('01 / Photography','Out in<br><em>the world.</em>','Photographs and albums from places along the way.')}<div class="filters" aria-label="Filter photographs">${categories.map((c,i)=>`<button class="filter ${i===0?'active':''}" aria-pressed="${i===0}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="collection">${data.photos.length?gallery(data.photos,true):'<p class="empty">The collection is coming soon.</p>'}</div>${demoNote()}`}
function research(){let previous=null;return `${intro('02 / Research & publications','Questions.<br><em>Then discoveries.</em>','Publications, organised by year — newest first.')}<div>${data.papers.length?data.papers.map((p,i)=>{const y=p.year||'Undated';const heading=y!==previous?`<h2 class="year-heading">${esc(y)}</h2>`:'';previous=y;return heading+paperCard(p,i)}).join(''):'<div class="empty"><h2>Research will appear here.</h2><p>Published papers, abstracts, and links to the original publications will be collected here.</p></div>'}</div>`}
function workCard(p,i){const images=imagesOf(p);return `<article class="work-card">${images.length?`<button class="photo-button" data-work="${i}" aria-label="View ${esc(p.title)}"><img src="${esc(imageURL(images[0].src))}" alt="${esc(images[0].alt||p.title)}" loading="lazy"><span class="image-count">${images.length} ${images.length===1?'image':'images'} ↗</span></button>`:''}<div class="work-copy"><div class="eyebrow">${esc(p.category||'Design')} ${p.year?' / '+esc(p.year):''}</div><h2>${esc(p.title)}</h2>${p.role?`<div class="meta">${esc(p.role)}</div>`:''}${p.description?`<p>${esc(p.description)}</p>`:''}${p.url?`<a class="text-link" href="${esc(safeURL(p.url))}" target="_blank" rel="noopener noreferrer">View project ↗</a>`:''}</div></article>`}
function otherWork(){return `${intro('03 / Design','Made to<br><em>connect.</em>','Design projects, marketing materials, and visual work.')}<div class="work-grid">${data.works.length?data.works.map(workCard).join(''):'<div class="empty"><h2>Work will appear here.</h2></div>'}</div>`}
function showViewer(i){photoIndex=(i+viewer.length)%viewer.length;const p=viewer[photoIndex];$('#lightbox img').src=imageURL(p.src);$('#lightbox img').alt=p.alt||p.title;$('.lightbox-caption').innerHTML=`<strong>${esc(p.title)}</strong>${p.location?' · '+esc(p.location):''}${p.caption?`<p class="lightbox-story">${esc(p.caption)}</p>`:''}${p.credit?`<div class="small"><a href="${esc(safeURL(p.source))}" target="_blank" rel="noopener noreferrer">${p.demo?'Demo photograph · ':''}${esc(p.credit)}</a></div>`:''}`;$('#photo-position').textContent=`${photoIndex+1} / ${viewer.length}`;$('#previous').disabled=$('#next').disabled=viewer.length<2;if(!$('#lightbox').open)$('#lightbox').showModal()}
function openPhoto(i){const p=shownPhotos[i],images=imagesOf(p);if(images.length>1){viewer=images.map(img=>({...p,...img}));showViewer(0)}else{viewer=shownPhotos.map(post=>({...post,...imagesOf(post)[0]}));showViewer(i)}}
function bindPhotoButtons(){document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(Number(b.dataset.photo)))}
function bindPublic(){bindPhotoButtons();document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});$('#collection').innerHTML=gallery(data.photos.filter(p=>b.dataset.filter==='All'||p.category===b.dataset.filter),true);bindPhotoButtons()});document.querySelectorAll('[data-share]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(safeURL(data.papers[Number(b.dataset.share)].url));toast('Paper link copied')}catch{toast('Open the paper and copy its address to share.')}});document.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{const p=data.works[Number(b.dataset.work)];viewer=imagesOf(p).map(img=>({...p,caption:p.description,...img}));showViewer(0)})}
function chooseHeroTone(pixels){let luminance=0,count=0;for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]<128)continue;const linear=c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4};luminance+=.2126*linear(pixels[i])+.7152*linear(pixels[i+1])+.0722*linear(pixels[i+2]);count++}return count&&luminance/count>.42?'dark':'light'}
function sectionOpening(kind,classes){const src=data.profile[kind+'Background'];return `<section id="${kind}" class="section ${classes} ${src?'photo-section':''}" data-background="${kind}" data-text-tone="light">${src?`<img class="section-backdrop" src="${esc(imageURL(src))}" alt="" loading="lazy">`:''}`}
function homeAbout(){const p=data.profile;return `${sectionOpening('about','journal-about full-about')}<div class="about-heading reveal"><div class="eyebrow">04 / A little about me</div><h2>Behind<br><em>the work.</em></h2><p class="section-intro">Researcher. Traveler. Designer.<br>Always looking a little closer.</p>${p.portrait?`<img class="home-portrait" src="${esc(imageURL(p.portrait))}" alt="Portrait of ${esc(p.name)}" loading="lazy">`:''}</div><div class="section-panel about-content reveal"><div class="eyebrow">Hello, I’m</div><h3>${esc(p.name)}</h3>${p.role?`<p class="about-role">${esc(p.role)}</p>`:''}${p.location?`<div class="about-location">${esc(p.location)}</div>`:''}<p class="biography">${esc(p.bio)}</p>${p.field&&p.field!=='Your research field'?`<div class="about-interests"><div class="eyebrow">Research interests</div><p>${esc(p.field)}</p></div>`:''}<div class="contact-links">${p.email?`<a href="mailto:${esc(p.email)}">Email me ↗</a>`:''}${p.links.map(l=>`<a href="${esc(safeURL(l.url))}" target="_blank" rel="noopener noreferrer">${esc(l.label)} ↗</a>`).join('')}</div></div></section>`}
function homeDesign(){const project=data.works[0];return `${sectionOpening('design','journal-design')}<div class="reveal"><div class="eyebrow">03 / Design</div><h2>Made to<br><em>connect.</em></h2><p class="section-intro">Visual stories. Thoughtful details.<br>Ideas that find their form.</p></div><div class="section-panel design-feature reveal"><div class="eyebrow">${project?'From the design collection':'Design & visual storytelling'}</div>${project?`<h3>${esc(project.title)}</h3><div class="design-meta">${esc(project.category||'Design')}${project.year?' / '+esc(project.year):''}</div><p>${esc(project.description||'Explore this project and more from my design collection.')}</p>`:'<h3>A space for ideas.</h3><p>Design projects and marketing materials will appear here.</p>'}<a class="section-link" href="other-work.html">Explore design projects <span>↗</span></a></div></section>`}
function home(){const photos=homePhotos(),profile=data.profile,backdrop=profile.heroBackground?{src:profile.heroBackground,title:'Selected homepage background'}:featuredPhoto();return `<section class="journal-intro ${backdrop?'photo-intro':''}" data-text-tone="light">${backdrop?`<img class="intro-backdrop" src="${esc(imageURL(backdrop.src))}" alt="${esc(backdrop.alt||backdrop.title)}" fetchpriority="high">`:''}<div><div class="eyebrow">The personal journal of ${esc(profile.headerName.replace(/\.$/,''))}</div><h1>A curious mind.<br>A wandering <em>eye.</em></h1></div><div class="journal-summary"><p>${esc(profile.intro)}</p><a class="text-link" href="photography.html">Explore the photographs <span>↘</span></a></div></section><nav class="chapter-nav" aria-label="Homepage sections"><a href="#photographs"><span>01</span> Photographs</a><a href="#research"><span>02</span> Research</a><a href="#design"><span>03</span> Design</a><a href="#about"><span>04</span> About me</a></nav><section id="photographs" class="section journal-photos"><div class="section-head reveal"><div><div class="eyebrow">01 / Selected photographs</div><h2>Fresh from the road.</h2></div><span class="meta">${String(photos.length).padStart(2,'0')} ${photos.some(p=>imagesOf(p).length>1)?'POSTS':'PHOTOGRAPHS'}</span></div>${demoNote()}${photos.length?homeGallery(photos):'<p class="empty">The collection is coming soon.</p>'}<a class="section-link" href="photography.html">All photographs <span>↗</span></a></section>${sectionOpening('research','research-section')}<div class="research-intro reveal"><div class="eyebrow">02 / Research & publications</div><h2>Ideas worth<br><em>exploring.</em></h2><p>${esc(profile.field&&profile.field!=='Your research field'?profile.field:'Questions, discoveries, and published work from my research journey.')}</p><span class="journal-monogram" aria-hidden="true">[ ${esc(profile.headerName.charAt(0))}. ]</span></div><div class="latest-research section-panel reveal"><div class="research-label">Latest research <span>${String(Math.min(1,data.papers.length)).padStart(2,'0')}</span></div>${data.papers.length?paperCard(data.papers[0],0):'<div class="research-empty"><h3>A space for discovery.</h3><p>My published research will be collected here.</p></div>'}<a class="section-link" href="research.html">All research <span>↗</span></a></div></section>${homeDesign()}${homeAbout()}`}
function setPhotoContrast(region,display,mode){region.dataset.textTone=mode==='dark'?'dark':'light';const fail=()=>{region.classList.remove('photo-intro','photo-section');display.hidden=true};display.addEventListener('error',fail,{once:true});if(display.complete&&!display.naturalWidth){fail();return}if(mode==='light'||mode==='dark')return;
const sample=new Image();sample.crossOrigin='anonymous';sample.onload=()=>{const analyze=()=>{try{const w=region.clientWidth,h=region.clientHeight,scale=Math.max(w/sample.naturalWidth,h/sample.naturalHeight),sw=w/scale,sh=h/scale;const canvas=document.createElement('canvas');canvas.width=64;canvas.height=40;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(sample,(sample.naturalWidth-sw)/2,(sample.naturalHeight-sh)/2,sw,sh,0,0,64,40);region.dataset.textTone=chooseHeroTone(ctx.getImageData(0,0,64,40).data)}catch{region.dataset.textTone='light'}};analyze();new ResizeObserver(analyze).observe(region)};sample.onerror=()=>{region.dataset.textTone='light'};sample.src=display.src}
function applyHeroContrast(){const hero=$('.photo-intro');if(hero)setPhotoContrast(hero,hero.querySelector('.intro-backdrop'),data.profile.heroTextTone||'auto');document.querySelectorAll('.photo-section').forEach(region=>setPhotoContrast(region,region.querySelector('.section-backdrop'),data.profile[region.dataset.background+'TextTone']||'auto'))}
function enhanceHomepage(){if(page!=='index')return;enhancePhotoCarousel();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('reveal-ready');observer.observe(el)})}const progress=document.createElement('div');progress.className='reading-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);let scheduled=false;const update=()=>{const distance=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${distance>0?Math.max(0,Math.min(1,scrollY/distance)):0})`;scheduled=false};addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update();document.querySelectorAll('#site-menu a[href*="#"]').forEach(a=>a.addEventListener('click',()=>$('#site-menu').close()));if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView())}

async function init(){try{const r=await fetch('content.json');if(!r.ok)throw Error('Could not load content');data=normalize(await r.json());document.body.dataset.page=page;$('#brand-name').textContent=data.profile.headerName;$('#copyright').textContent=`© ${new Date().getFullYear()} ${data.profile.name}`;$('#footer-name').textContent=data.profile.headerName;document.title=`${({index:'Portfolio',photography:'Photography',research:'Research','other-work':'Design',about:'About',})[page]||'Portfolio'} — ${data.profile.headerName}`;document.querySelectorAll(`[data-page="${page}"]`).forEach(a=>a.setAttribute('aria-current','page'));$('#main').innerHTML=page==='photography'?photography():page==='research'?research():page==='other-work'?otherWork():home();bindPublic();applyHeroContrast();enhanceHomepage()}catch(e){$('#main').innerHTML='<div class="error"><h1>Unable to load.</h1><p>Check that content.json is present, and open this website through GitHub Pages or a local web server.</p></div>';console.error(e)}}
$('#menu-toggle').onclick=()=>$('#site-menu').showModal();$('#menu-close').onclick=()=>$('#site-menu').close();$('.close').onclick=()=>$('#lightbox').close();$('#previous').onclick=()=>showViewer(photoIndex-1);$('#next').onclick=()=>showViewer(photoIndex+1);$('#lightbox').addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close()});document.addEventListener('keydown',e=>{if($('#lightbox').open){if(e.key==='ArrowLeft')showViewer(photoIndex-1);if(e.key==='ArrowRight')showViewer(photoIndex+1)}});
init();
